services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kinlink-be-app
    container_name: kinlink-be-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - kinlink-network

  web:
    image: nginx:alpine
    container_name: kinlink-be-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - kinlink-network

  db:
    image: mariadb:10.11
    container_name: kinlink-be-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kinlink-network

networks:
  kinlink-network:
    driver: bridge

volumes:
  db_data:
